### PR TITLE
Move Functionality Overview to new main section Features

### PR DESCRIPTION
**Pull request by engineering-this**
Renamed `Functionality Overview` category into `Features Overview` and changed it into new section. This required changing plenty of links. Also there will be another PR in https://github.com/ckeditor/ckeditor-dev

As a follow-up links in https://github.com/WebSpellChecker/ckeditor-plugin-scayt should be updated.

`[documentation](#!/guide/dev_spellcheck)`
to
`{@glink features/spellcheck documentation}`

### CODE REVIEW

**Comment by engineering-this** [comment]
Here is the other PR: ckeditor/ckeditor-dev#3109
👆 Remember to checkout `ckeditor-dev` on that branch, and run build docs with `-dev` flag.

**Comment by f1ames** [comment]
As already mentioned in https://github.com/ckeditor/ckeditor-dev/issues/2992#issuecomment-493441674, since this PR also requires changes in `ckeditor-dev` it needs to target `major` branch to be released together with CKEditor.

@engineering-this Could you rebase it (or move on top of `major` by `cherry picking` - not sure which will be easier) and target this PR to `major` branch?

**Comment by f1ames** [comment]
Ok, I have extracted an issue for SCAYT/WSC links https://github.com/ckeditor/ckeditor-dev/issues/3178 so we can proceed with this PR. And we will keep https://github.com/ckeditor/ckeditor-dev/issues/2992 open untill the redirects map will be provided (mentioned in https://github.com/ckeditor/ckeditor-docs/pull/249#pullrequestreview-250184818).

**Comment by f1ames** [comment]
Rebased on the latest `master`.

**Comment by engineering-this** [comment]
Total links: 47.

There are 46 catalogues in `features/`
Plus `index.html`, so it sums to 47, should be OK, but could you check if it looks OK to you @f1ames?

```
	[ {
		from: 'guide/dev_features.html',
		to: 'features/index.html'
	}, {
		from: 'guide/dev_accessibility_checker.html',
		to: 'features/accessibility_checker.html'
	}, {
		from: 'guide/dev_autocomplete.html',
		to: 'features/autocomplete.html'
	}, {
		from: 'guide/dev_autogrow.html',
		to: 'features/autogrow.html'
	}, {
		from: 'guide/dev_balloontoolbar.html',
		to: 'features/balloontoolbar.html'
	}, {
		from: 'guide/dev_basicstyles.html',
		to: 'features/basicstyles.html'
	}, {
		from: 'guide/dev_bbcode.html',
		to: 'features/bbcode.html'
	}, {
		from: 'guide/dev_codesnippet.html',
		to: 'features/codesnippet.html'
	}, {
		from: 'guide/dev_codesnippetgeshi.html',
		to: 'features/codesnippetgeshi.html'
	}, {
		from: 'guide/dev_colorbutton.html',
		to: 'features/colorbutton.html'
	}, {
		from: 'guide/dev_copyformatting.html',
		to: 'features/copyformatting.html'
	}, {
		from: 'guide/dev_devtools.html',
		to: 'features/devtools.html'
	}, {
		from: 'guide/dev_drop_paste.html',
		to: 'features/drop_paste.html'
	}, {
		from: 'guide/dev_easyimage.html',
		to: 'features/easyimage.html'
	}, {
		from: 'guide/dev_media_embed.html',
		to: 'features/media_embed.html'
	}, {
		from: 'guide/dev_emoji.html',
		to: 'features/emoji.html'
	}, {
		from: 'guide/dev_enterkey.html',
		to: 'features/enterkey.html'
	}, {
		from: 'guide/dev_format.html',
		to: 'features/format.html'
	}, {
		from: 'guide/dev_fullpage.html',
		to: 'features/fullpage.html'
	}, {
		from: 'guide/dev_image.html',
		to: 'features/image.html'
	}, {
		from: 'guide/dev_image2.html',
		to: 'features/image2.html'
	}, {
		from: 'guide/dev_magicline.html',
		to: 'features/magicline.html'
	}, {
		from: 'guide/dev_mathjax.html',
		to: 'features/mathjax.html'
	}, {
		from: 'guide/dev_mentions.html',
		to: 'features/mentions.html'
	}, {
		from: 'guide/dev_notifications.html',
		to: 'features/notifications.html'
	}, {
		from: 'guide/dev_output_format.html',
		to: 'features/output_format.html'
	}, {
		from: 'guide/dev_pastefromexcel.html',
		to: 'features/pastefromexcel.html'
	}, {
		from: 'guide/dev_pastefromword.html',
		to: 'features/pastefromword.html'
	}, {
		from: 'guide/dev_placeholder.html',
		to: 'features/placeholder.html'
	}, {
		from: 'guide/dev_readonly.html',
		to: 'features/readonly.html'
	}, {
		from: 'guide/dev_removeformat.html',
		to: 'features/removeformat.html'
	}, {
		from: 'guide/dev_resize.html',
		to: 'features/resize.html'
	}, {
		from: 'guide/dev_sharedspace.html',
		to: 'features/sharedspace.html'
	}, {
		from: 'guide/dev_shortcuts.html',
		to: 'features/shortcuts.html'
	}, {
		from: 'guide/dev_size.html',
		to: 'features/size.html'
	}, {
		from: 'guide/dev_sourcearea.html',
		to: 'features/sourcearea.html'
	}, {
		from: 'guide/dev_spellcheck.html',
		to: 'features/spellcheck.html'
	}, {
		from: 'guide/dev_styles.html',
		to: 'features/styles.html'
	}, {
		from: 'guide/dev_tabindex.html',
		to: 'features/tabindex.html'
	}, {
		from: 'guide/dev_table.html',
		to: 'features/table.html'
	}, {
		from: 'guide/dev_toolbar.html',
		to: 'features/toolbar.html'
	}, {
		from: 'guide/dev_toolbarconcepts.html',
		to: 'features/toolbarconcepts.html'
	}, {
		from: 'guide/dev_toolbarlocation.html',
		to: 'features/toolbarlocation.html'
	}, {
		from: 'guide/dev_uicolor.html',
		to: 'features/uicolor.html'
	}, {
		from: 'guide/dev_uicolorpicker.html',
		to: 'features/uicolorpicker.html'
	}, {
		from: 'guide/dev_uilanguage.html',
		to: 'features/uilanguage.html'
	}, {
		from: 'guide/dev_uitypes.html',
		to: 'features/uitypes.html'
	} ];
```

**Pull request merged**
