### PR TITLE
Move samples building to docs repository

### PR DESCRIPTION
**Pull request by msamsel**
Make possibility to build Examples together with Documentation inside the same layout.
- move all samples from https://github.com/ckeditor/ckeditor-sdk
- add submodules required by samples (ckeditor-presets and ckeditor-docs-samples)
- add grunt command to build sdk -> building editor in presets and copy to samples
- fix links in docs descriptions and samples description
- modify samples to contain required by umberto meta informations
- modify Umberto config to build examples section
- provide common config, which is injected to config.js file, for every samples

related to https://github.com/ckeditor/ckeditor-sdk/issues/259
~required https://github.com/cksource/umberto/pull/582 to work properly~ Umberto v0.8.0

### CODE REVIEW

**Comment by msamsel** [comment]
@mlewand, branch is updates and ready for review.

**Comment by mlewand** [comment]
Thanks, yes it's about time we move this project now after the 4.11.0 release.

**Comment by msamsel** [comment]
> It make sense to use fs-extra module that provides a nice wrapper to the native fs. This will allow to eliminate promisify.js module and greatly increase readability of the scripts.

👍

> This "documentation" link (under sdk examples header) was not yet addressed. It has this full (block) width focus area. Also in current shape it consumes substantial amount of vertical space.

https://github.com/cksource/umberto/issues/681

> There are still some sdk.ckeditor.com domain references:

👍 

> ckeditor-docs/README.md there's "Developer documentation is a part of CKEditor SDK.". This part is no longer relevant and should be removed.

👍 (replaced `CKEditor SDK` to `CKEditor Examples`)

> https://github.com/ckeditor/ckeditor-docs/blob/dcd6e35/docs/guide/dev/basics/README.md#L53 - "Visit the CKEditor SDK to see " should be reworded, it should say about visiting examples section.

👍 

> Balloon toolbar sample has a broken image link (in editor content). On current SDK it points to https://sdk.ckeditor.com/samples/assets/image2/spoons.jpg.

👍 

> http://docs.ckeditor.test/docs/ckeditor4/latest/examples/acf.html - textarea below "The following text will be used in each sample to show different filtering options:" section leaks outside of the wrapper.

👍 

> Here in code: https://github.com/ckeditor/ckeditor-docs/blob/dcd6e35/gruntfile.js#L22 it should be named examples now.

👍 

> Submodules should use https rather than ssh protocol (I'm talking about ckeditor-presets and ckeditor-docs-samples).

👍

**Comment by msamsel** [comment]
I just left info here to not forget in the future.
Dependencies of `rimraf` and `ncp` should be removed from `package.json`.

**Comment by msamsel** [comment]
I've made all required changes.
⚠️ There was also change in dependencies!

I've made additional change here, add `<br>` element before link to documentation. It's important to have it right now, because bigbang-docs usually use newer version of Umberto, this would desync styling of this link and will just look bad for the user. (Link would became inline again with some new Umberto version, but html won't be updated in ckeditor-docs). I don't want to add some hidden magic in Umberto, which will fix it, as later this would be hard to maintain, that some not defined element will magically appear in output.

To have sure that link to documentation will look ok, for both ckeditor-docs and bigbang-docs, and have sure that it won't change in near future I had to update umberto together with update of those links.

**Comment by mlewand** [comment]
Change added in 745e7902db2ae5f81e05760141220438afed41e8 is a no go, instead of adding `<br>`s everywhere this change should be added once in CSS only. @msamsel asked me to remove this commit from history, so that's what I'm going to do and the branch will be force pushed in few mins.

**Pull request merged**
